In [1]:
 import os
os.getcwd()

'C:\\Users\\kran0007'

In [2]:
os.chdir('C:/Users/kran0007/Downloads')

In [3]:
import pandas as pd 
data=pd.read_csv('iris.csv') 
data.head() 

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
data['Species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
colnames=data.columns.values.tolist() 
predictors=colnames[:4] 
target=colnames[4] 

In [7]:
# Load the library with the iris dataset
from sklearn.datasets import load_iris

# Load scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier

# Load pandas
import pandas as pd

# Load numpy
import numpy as np

# Set random seed
np.random.seed(0)                                    

In [8]:
# Create an object called iris with the iris data
iris = load_iris()

# Create a dataframe with the four feature variables
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# View the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
# Add a new column with the species names, this is what we are going to try to predict
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

# View the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [10]:
# Create a new column that for each row, generates a random number between 0 and 1, and
# if that value is less than or equal to .75, then sets the value of that cell as True
# and false otherwise. This is a quick and dirty way of randomly assigning some rows to
# be used as the training data and some as the test data.
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75

# View the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [13]:
# Create two new dataframes, one with the training rows, one with the test rows
train, test = df[df['is_train']==True], df[df['is_train']==False]

In [14]:
# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 118
Number of observations in the test data: 32


In [15]:
# Create a list of the feature column's names
features = df.columns[:4]

# View features
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [16]:
# train['species'] contains the actual species names. Before we can use it,
# we need to convert each species name into a digit. So, in this case there
# are three species, which have been coded as 0, 1, or 2.
y = pd.factorize(train['species'])[0]

# View target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [17]:
# Create a random forest Classifier. By convention, clf means 'Classifier'
clf = RandomForestClassifier(n_jobs=2, random_state=0)

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(train[features], y)

C:\Users\kran0007\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [18]:
# Apply the Classifier we trained to the test data (which, remember, it has never seen before)
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [19]:
# View the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[0:10]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [20]:
# Create actual english names for the plants for each predicted plant class
preds = iris.target_names[clf.predict(test[features])]

In [21]:
# View the PREDICTED species for the first five observations
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [22]:
# View the ACTUAL species for the first five observations
test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [23]:
# Create confusion matrix
pd.crosstab(test['species'], preds, rownames=['Actual Species'], colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [24]:
# View a list of the features and their importance scores
list(zip(train[features], clf.feature_importances_))

[('sepal length (cm)', 0.11185992930506346),
 ('sepal width (cm)', 0.016341813006098178),
 ('petal length (cm)', 0.36439533040889194),
 ('petal width (cm)', 0.5074029272799464)]

In [26]:
import pandas as pd 
data=pd.read_csv('Boston.csv') 
data.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [27]:
colnames=data.columns.values.tolist() 
predictors=colnames[:13] 
target=colnames[13] 
X=data[predictors] 
Y=data[target] 

In [29]:
from sklearn.tree import DecisionTreeRegressor 
regression_tree = DecisionTreeRegressor(min_samples_split=30,min_samples_leaf=10,random_state=0) 
regression_tree.fit(X,Y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=10,
           min_samples_split=30, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [30]:
reg_tree_pred=regression_tree.predict(data[predictors]) 
data['pred']=reg_tree_pred 
cols=['pred','medv'] 
data[cols]

pred  medv
0    22.840000  24.0
1    22.840000  21.6
2    35.247826  34.7
3    35.247826  33.4
4    35.247826  36.2
5    24.058621  28.7
6    20.811111  22.9
7    20.020833  27.1
8    20.020833  16.5
9    20.020833  18.9
10   20.020833  15.0
11   20.811111  18.9
12   20.020833  21.7
13   20.624138  20.4
14   18.750000  18.2
15   20.624138  19.9
16   20.624138  23.1
17   19.408333  17.5
18   20.292308  20.2
19   20.292308  18.2
20   14.041667  13.6
21   18.750000  19.6
22   15.628000  15.2
23   14.041667  14.5
24   15.628000  15.6
25   15.628000  13.9
26   15.628000  16.6
27   15.628000  14.8
28   18.750000  18.4
29   18.750000  21.0
..         ...   ...
476  15.628000  16.7
477  12.630000  12.0
478  13.922222  14.6
479  20.783333  21.4
480  20.783333  23.0
481  27.247826  23.7
482  28.978261  25.0
483  20.783333  21.8
484  20.783333  20.6
485  20.783333  21.2
486  19.408333  19.1
487  20.783333  20.6
488  18.112500  15.2
489  14.041667   7.0
490  14.041667   8.1
491  18.112500  13.6
492  20.783333  20.1
493  20.292308  21.8
494  20.292308  24.5
495  19.408333  23.1
496  14.041667  19.7
497  18.750000  18.3
498  20.292308  21.2
499  19.408333  17.5
500  18.750000  16.8
501  22.840000  22.4
502  20.624138  20.6
503  28.978261  23.9
504  31.170000  22.0
505  20.624138  11.9

[506 rows x 2 columns]

In [41]:
from sklearn.model_selection import KFold 
from sklearn.model_selection import cross_val_score 
import numpy as np 
crossvalidation = KFold(n_splits=X.shape[0],shuffle=True, random_state=1) 
score = np.mean(cross_val_score(regression_tree, X, Y, cv=crossvalidation,n_jobs=1)) 
score

0.0

In [42]:
regression_tree.feature_importances_

array([0.03421203, 0.        , 0.00116059, 0.        , 0.01856163,
       0.6308568 , 0.01725115, 0.00137451, 0.        , 0.00236983,
       0.00933325, 0.        , 0.28488021])

In [43]:
from sklearn.ensemble import RandomForestRegressor 
rf = RandomForestRegressor(n_jobs=2,oob_score=True,n_estimators=10) 
rf.fit(X,Y) 

C:\Users\kran0007\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:732: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
           oob_score=True, random_state=None, verbose=0, warm_start=False)

In [44]:
rf.oob_prediction_

array([28.28333333, 23.16666667, 31.45      , 37.5       , 36.225     ,
       24.42      , 20.        , 17.        , 18.275     , 20.72      ,
       21.7       , 22.5       , 19.8       , 19.7       , 20.875     ,
       20.4       , 22.        , 18.85      , 17.93333333, 20.2       ,
       14.3       , 20.18      , 18.06666667, 14.16      , 16.3       ,
       15.325     , 17.83333333,  0.        , 23.        , 21.025     ,
       13.65      , 19.76      , 13.9       , 14.4       , 13.7       ,
       22.175     , 20.275     , 20.04      , 21.5       , 28.48      ,
       34.9       , 32.46      , 23.06      , 22.05      , 22.25      ,
       19.        , 20.38      , 18.94      , 18.2       , 19.74      ,
       21.6       , 22.725     , 25.8       , 20.35      , 19.93333333,
       35.23333333, 23.43333333, 30.525     , 23.0625    , 21.63333333,
       18.625     , 20.1       , 24.9       , 26.85      , 34.14      ,
       25.075     , 19.7       , 20.38      , 19.98      , 21.3 

In [45]:
data['rf_pred']=rf.oob_prediction_ 
cols=['rf_pred','medv'] 
data[cols].head() 

rf_pred  medv
0  28.283333  24.0
1  23.166667  21.6
2  31.450000  34.7
3  37.500000  33.4
4  36.225000  36.2

In [46]:
data['rf_pred']=rf.oob_prediction_ 
data['err']=(data['rf_pred']-data['medv'])**2 
sum(data['err'])/506 

17.366990597433333

In [47]:
rf.oob_score_

0.7942776367444222